### ISSUE TITLE
Parsing data in ui.form is broken in webix 9

### ISSUE THREAD

**Issue by remixer-dec** [webix-hub/webix#343]
[form.parse](https://docs.webix.com/api__link__ui.form_parse.html) with parameter clear = true does not work in webix 9, but it works in webix 8.4.   
error in console:  
_TypeError: this.clearAll is not a function_

code: https://snippet.webix.com/60xv5uqn
